### ISSUE TITLE
importing packages from `pub.dev`

### ISSUE THREAD

**Issue by hemangjoshi37a** [flet-dev/flet#1067]
How to import packages from `pub.dev` into python flet development environment?

**Comment by FeodorFitsner** [comment]
It's not possible because `pub.dev` hosts packages in Dart which cannot be imported into Python.
To make some Dart package work in Flet it must be "implemented" on both Python and Dart sides of Flet framework.
Look at this example of implementing an abstract control in Flet: https://github.com/flet-dev/flet/pull/428/files

**Comment by hemangjoshi37a** [comment]
can we design a generalized transpiler that does this 

> it must be "implemented" on both Python and Dart sides of Flet framework

automatically ?

**Comment by hemangjoshi37a** [comment]
also please review my PR : #1066

**Comment by JarriqTheTechie** [comment]
> can we design a generalized transpiler that does this 
> 
> 
> 
> > it must be "implemented" on both Python and Dart sides of Flet framework
> 
> 
> 
> automatically ?

Following..
