### ISSUE TITLE
Upload files with file picker

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#109]
https://pub.dev/packages/file_picker
https://stackoverflow.com/questions/58793993/how-to-convert-uint8list-image-to-file-image-for-upload-in-flutter-web
https://stackoverflow.com/questions/56252856/how-to-pick-files-and-images-for-upload-with-flutter-web

https://stackoverflow.com/a/51195811/1435891
https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ
https://gin-gonic.com/docs/examples/upload-file/single-file/
https://www.codegrepper.com/code-examples/whatever/Upload+multiple+images+in+flutter+by+multipart
https://gist.github.com/FeodorFitsner/d1fcc9b8cfd53ebd7f6a29f4d5176d59

**Comment by seth-c-stenzel** [comment]
I would also like to see things; this is a must-have for me, and the scripts that I generally create for my team which are generally utility scripts and me. I tried to implement something with PySimpleGui and easygui but because of how the windows are spawned, there is some wonky behavior with how the dialogue is created, and it seems to always be created beneath the Flutter app window.

**Comment by ssinghm32** [comment]
+1  

I would also be interested in a FilePicker / Uploader control within Flet.  

Most business applications require some sort of document upload into the system.

Thanks

**Comment by fauzaanu** [comment]
+1 This will be very useful.

**Comment by 99hats** [comment]
+1

**Comment by shanerigby** [comment]
+1

**Comment by FeodorFitsner** [comment]
I'm working on it...

**Comment by lwanger** [comment]
+1!

**Comment by FeodorFitsner** [comment]
https://flet.dev/blog/file-picker-and-uploads/
