### ISSUE TITLE
[Feature Request]  `Control`: add ref property and setter method

### ISSUE THREAD

**Issue by eeintech** [flet-dev/flet#1112]
**Please Describe The Problem To Be Solved**

1. Define the Ref and Control independently at first
``` python
tf_ref = ft.Ref[ft.TextField]()

tf_field= ft.TextField(
  label='first_name',
)
```
2. Attach the `Ref` to the control when building view, for instance:
``` python
tf_field.ref = tf_ref
tf_field.update()
```

**(Optional): Suggest A Solution**

Make the `ref` attribute a property and add a setter method:
``` python
@property
def ref(self):
  return self._ref

@ref.setter
def ref(self, ref):
  if type(ref) == ft.Ref:
    ref.current = self
    self._ref = ref
```

**Comment by iron3oxide** [comment]
Have a look at #839. The conclusion was that it shouldn't be needed if you design your app properly. If you have a code sample that wouldn't work without it, please paste it as a reply.

**Comment by iron3oxide** [comment]
I dont see where you'd need to set the `ref` property in either code sample. Besides, why not add the `on_change` to the enable button when you create it? Also, checking if a field has a ref seems like an overly complicated way to determine if a field is optional, especially since (in your example) you should be able to know if a field is optional when you define it. 

Refs are useful when you want to access a control outside of the scope it was created in. IMO, you should always be able to know if you want to do that and thus pass the ref as a keyword argument to the control when you create it. I'm not even sure I see many valid use cases for the `ref.current` setter you use in lieu of that in the first example, since thinking of refs and controls as permanent one-to-one pairs seems much more logical to me. 

BTW, if you are building custom views and assign routes to them, you might be interested in [fletched](https://github.com/iron3oxide/fletched). Hope I could help a bit, lmk if you have any questions.

**Comment by eeintech** [comment]
> Besides, why not add the `on_change` to the enable button when you create it?

How would you do this? I wish I could do this but this isn't working:
``` python
fields = [
        ft.Switch(
            label='Enable',
            on_change=lambda e: self.enable_optional_fields(e),
        ),
```

> I dont see where you'd need to set the `ref` property in either code sample.

You are completely right on this, _however_ it seems much easier to me to just attempt to update _everything_ on the view and only hits (field with refs) will be updated. Maybe I'm missing the point or the method to achieve this with Felt.

> Refs are useful when you want to access a control outside of the scope it was created in. IMO, you should always be able to know if you want to do that and thus pass the ref as a keyword argument to the control when you create it. I'm not even sure I see many valid use cases for the `ref.current` setter you use in lieu of that in the first example, since thinking of refs and controls as permanent one-to-one pairs seems much more logical to me.

I guess I am missing the point of Refs. I'm no experienced programmer so I thought creating them dynamically when building the view instead of more static implementation would look a lot cleaner. It actually works quite nicely for my app with the workaround above, I even created a `SwitchWithRefs` control to go on and disable form fields associated to this switch.

> BTW, if you are building custom views and assign routes to them, you might be interested in [fletched](https://github.com/iron3oxide/fletched). Hope I could help a bit, lmk if you have any questions.

Thanks for sharing. Checking quickly I don't see what pain point is it solving?
Here are my app's GUI: https://github.com/sparkmicro/Ki-nTree/blob/main/kintree/gui/gui.py

What would Fletched do instead of using custom views?

**Comment by iron3oxide** [comment]
> How would you do this? I wish I could do this but this isn't working:

It should work like that though. Are you getting any error message?

> You are completely right on this, however it seems much easier to me to just attempt to update everything on the view and only hits (field with refs) will be updated. Maybe I'm missing the point or the method to achieve this with Felt.

> I guess I am missing the point of Refs. I'm no experienced programmer so I thought creating them dynamically when building the view instead of more static implementation would look a lot cleaner. It actually works quite nicely for my app with the workaround above, I even created a SwitchWithRefs control to go on and disable form fields associated to this switch when view is built.

You don't generate controls dynamically though as far as I can see. So why update them dynamically? Just mark them as optional when you create them, either by separating them into another list or other means. Also, you don't really need refs at all in this particular example, since you still have access to the fields they belong to. They're only really useful if you want to access the controls from somewhere outside their scope.

> Thanks for sharing. Checking quickly I don't see what pain point is it solving?
> Here are my app's GUI: https://github.com/sparkmicro/Ki-nTree/blob/main/kintree/gui/gui.py
> What would Fletched do instead of using custom views?

That depends on how much of fletched you want to use.

The `mvp` module exists to aid in using an MVP (Model-View-Presenter) architecture pattern in your code, leading (in theory) to better testability, separation of concerns and overall maintainability. Since your code seems non-trivial and you've already written lots of it, using the `mvp` module of `fletched` would require refactoring most of it, which would probably help you in the long run (imho), but can be tedious.

The `routed_app` module will do routing and route protection for you. Since you do that manually in a rather long if-elif-else statement right now, that might be a relief. But again, code will have to be rewritten and that's not always worth it, so be your own judge.

**Comment by eeintech** [comment]
> It should work like that though. Are you getting any error message?

The following error:
``` shell
    on_change=lambda e: self.enable_optional_fields(e),
NameError: name 'self' is not defined
```

Have I heard of Fletched before I would have given a shot. Also I don't really have need for permissions in my app.
Thanks for taking a look and giving me feedback, much appreciated.

**Comment by iron3oxide** [comment]
That error makes sense now that I see it. You'll probably want to use an `__init__()` method instead of class variables to set `route` and `fields`. Something like this:
```python
class CustomView(ft.View):
    def __init__(self):
        super().__init__(route = '/')
        self.fields = [
        ft.Switch(
            label='Enable',
            on_change=self.enable_optional_fields
        ),
        ft.TextField(
            label='Mandatory',
        ),
        ft.TextField(
            ref=ft.Ref[ft.TextField](),
            label='Optional 1',
            visible=False,
        ),
        ft.TextField(
            ref=ft.Ref[ft.TextField](),
            label='Optional 2',
            visible=False,
        ),
    ]
```
Note that you don't have to use a lambda expression here, `enable_optional_fields` will automatically be called with the event as its argument.

**Comment by eeintech** [comment]
@iron3oxide I somehow needed a refresher on the difference of class vs instance variables, which I did for my own sake..!
I often get confused mixing both because, as you mentioned, Python let us use class variables with the `self.` prefix, I feel like it shouldn't be allowed :sweat_smile: 
I will have to go back over my code to see how can it be improved to make proper use of each type, in the meantime I'm still adding more feature to my GUI, inefficiently slow but it is coming together, if you want to check it out:
``` shell
pip install --pre kintree
```

I guess this issue went quite off-topic and my reasoning is not strong enough to request this feature to be implemented, as you pointed out I twisted the use of Control Refs to my own sauce :smile: 

I do appreciate you taking the time to answer and make me realize few things along the way, highly appreciated!

**Comment by iron3oxide** [comment]
> I often get confused mixing both because, as you mentioned, Python let us use class variables with the self. prefix, I feel like it shouldn't be allowed 

Good point, however I find this to be quite useful in some cases. If you dig into the code of fletched, you will see that I used this behavior to make its API more declarative and cut down on boilerplate code the user has to write. I'm not sure yet if that's considered pythonic, but I wanted to prioritize Developer Experience.

> I do appreciate you taking the time to answer and make me realize few things along the way, highly appreciated!

No problem, glad I could help!

**Comment by eeintech** [comment]
@iron3oxide Did you decide to stop support of [fletched](https://github.com/iron3oxide/fletched)? I was going to revisit it for another app

**Comment by iron3oxide** [comment]
> @iron3oxide Did you decide to stop development and support for [fletched](https://github.com/iron3oxide/fletched)? I was going to revisit it for another app

Indeed, I am focussing on Rust at the moment. It may still work and be useful though, feel free to fork it.

**Comment by eeintech** [comment]
Thanks but in this case I rather use the barebone app instead of constructing my app with unsupported libraries ;)
