### ISSUE TITLE
Incorrect label type in the checkbox

### ISSUE THREAD

**Issue by Vlod-github** [flet-dev/flet#1286]
https://github.com/flet-dev/flet/blob/969cb2278a6e06e8abe669531c8839d7cb08bcf7/sdk/python/packages/flet-core/src/flet_core/checkbox.py#L166

The `_get_attr()` function returns Any, so you need to explicitly specify the type.
```python
    # label
    @property
    def label(self) -> Optional[str]:
        return self._get_attr("label")

    @label.setter
    def label(self, value: Optional[str]):
        self._set_attr("label", value)
```

**Comment by FeodorFitsner** [comment]
Are you going to submit PR for this and #1285?

**Comment by Vlod-github** [comment]
Yes, I can provide PR. However, the decision about #1285 is ambiguous. This is the behavior in many places of the project. When it is specified that the function accepts enum, however, inside it contains the isinstance() check and the logic of working with other types.

Perhaps this is done for backward compatibility, and the enum is specified so that new developers specify it. In any case, I see three solutions: leave as is, allow both enum and literal, or leave only enum and remove logic for other types. The first option postpones the problem and violates pep, the second option is applicable only if you think that the API should duplicate enum and literal, the third option may break backward compatibility with old projects and examples.

Since I am not a flet developer, it is not for me to decide how best. I only noticed it when my typechecker started swearing.

**Comment by ndonkoHenri** [comment]
@Vlod-github, Thanks for bringing back this annoying issue on the table.
A choice(a really good one) has to be made as you said. 
Some months back I made a PR (second option in your comment - having enums and literals), because like you, my typechecker was also crying all over the place.
@FeodorFitsner [said](https://github.com/flet-dev/flet/pull/697#issuecomment-1345624500) duplication wasn't a good idea.

> Also, the main question is how long are we going to maintain two versions of those enums and string literals in each case? My original idea was switching to enums all together, while allowing strings (fixed beartype checks), rewrite all current examples to use enums and let developers see type errors when strings are used, but not enums. Are we going to have double enum-strings for new controls? Probably not.
So, maybe "fixing" that doesn't make sense at all?

My notes:
- If I remember correctly, Flet has moved away from beartypes... so no more 'fixed beartype checks'.
- not everyone wants to use Enums.. Some like using strings.. and don't want to see these type errors. I haven't yet seen a python project/API which forces devs to use enums instead of strings... ('let developers see type errors when strings are used')
- Lastly, these Literals(ex MainAxisAlignmentString) are necessary in flet's source code itself. (Precisely at most of the `.setter` functions)
> When it is specified that the function accepts enum, however, inside it contains the isinstance() check and the logic of working with other types.


What's your opinion today on all this @FeodorFitsner ? 🤔

**Comment by Vlod-github** [comment]
I am also in favor of not duplicating the code and for leaving the enumeration. If users want strings, fine. But inside the framework it is better to use and store one type. Here is the next alternative that will remove the internal dependency on Literal.
```python
## utils
from enum import Enum
from typing import Optional, Type, TypeVar


T = TypeVar('T', bound=Enum)


def value_to_enum(enum: Type[T], value) -> Optional[T]:
    if isinstance(value, Enum):
        return value  # type: ignore
    return enum.__dict__['_value2member_map_'].get(value, None)
```
```python
## test
from enum import Enum
from typing import Optional, Literal, Union

from utils import value_to_enum

test_literal = Literal[
    "start",
    "end",
]


class TestEnum(Enum):
    START = "start"
    END = "end"


def check(param: Optional[Union[TestEnum, test_literal]]):
    enum_param: Optional[TestEnum] = value_to_enum(TestEnum, param)
    print(enum_param)


check("start")
check(TestEnum.START)
```

**Comment by Vlod-github** [comment]
Because now the following problem arises, which concerns operations with object fields:
```python
from flet_core import Row, MainAxisAlignment

row_a = Row(alignment=MainAxisAlignment.START)
row_b = Row(alignment="start")
assert row_a.alignment == row_b.alignment #  Error
```
