### ISSUE TITLE
Video and Webview

### ISSUE THREAD

**Issue by cuifengcn** [flet-dev/flet#1739]
**Greetings! Have you contemplated elevating the development priority of the video and webview functionalities, considering their immense practicality?**

**Comment by FeodorFitsner** [comment]
Closing as dup of #257 and #432

**Comment by vindevoy** [comment]
Just for my understanding, if I would want to test this already, can I just checkout a branch ?  I see that a lot of controls on the roadmap towards the end of the year are completed.  I am really waiting for a couple of them because they are in the existing version of an application I wrote.  As a proof of concept, I would like to rewrite my GUI in Flet once these controls become available

**Comment by FeodorFitsner** [comment]
Of course, you can always test with a dev/feature branch.
For adding controls we are going to have "light" pull requests adding 1-2 controls which are merged into `main` and available as "dev" packages on pypi.org.
