### ISSUE TITLE
Android-Cam

### ISSUE THREAD

**Issue by ixelizm** [flet-dev/flet#1950]
Is it possible to open the camera of my Android device from the web page? In other words, it will ask for permission to use the camera and my device's camera will be turned on. I can do that?

**Comment by ndonkoHenri** [comment]
https://github.com/flet-dev/flet/issues/1281

**Comment by ixelizm** [comment]
Not PC camera i want to phone camera. like omegle

**Comment by frankhuurman** [comment]
Camera is still on the roadmap: https://flet.dev/roadmap/#september-2023---january-2024
And I can't find any Camera documentation in the framework so I assume there's no working camera element yet.

**Comment by Python-Zhao** [comment]
How is kivy implemented?

**Comment by Python-Zhao** [comment]
This example demonstrates a simple use of the camera. It shows a window with
a buttoned labelled 'play' to turn the camera on and off. Note that
not finding a camera, perhaps because gstreamer is not installed, will
throw an exception during the kv language processing.

'''

# Uncomment these lines to see all the messages
# from kivy.logger import Logger
# import logging
# Logger.setLevel(logging.TRACE)

from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
import time
Builder.load_string('''
<CameraClick>:
    orientation: 'vertical'
    Camera:
        id: camera
        resolution: (640, 480)
        play: False
    ToggleButton:
        text: 'Play'
        on_press: camera.play = not camera.play
        size_hint_y: None
        height: '48dp'
    Button:
        text: 'Capture'
        size_hint_y: None
        height: '48dp'
        on_press: root.capture()
''')


class CameraClick(BoxLayout):
    def capture(self):
        '''
        Function to capture the images and give them the names
        according to their captured time and date.
        '''
        camera = self.ids['camera']
        timestr = time.strftime("%Y%m%d_%H%M%S")
        camera.export_to_png("IMG_{}.png".format(timestr))
        print("Captured")


class TestCamera(App):

    def build(self):
        return CameraClick()


TestCamera().run()

**Comment by ndonkoHenri** [comment]
Closing as dup of https://github.com/flet-dev/flet/issues/1281
