### ISSUE TITLE
`fletd` download failed when running program in windows

### ISSUE THREAD

**Issue by tomasky** [flet-dev/flet#202]
i think should  make the download url configurable,because some places are slow to download from github release

**Comment by FeodorFitsner** [comment]
The thing is "fletd" (along with Flet view app) comes bundled with Python module, in package's "bin" folder and does not require a download.

Could you run the following "test" app with logs enabled to see what's going on:

```python
import logging

import flet
from flet import Page, Text

logging.basicConfig(level=logging.DEBUG)

def main(page: Page):
    page.add(Text("Hello!"))

flet.app(target=main, view=flet.FLET_APP)
```

**Comment by FeodorFitsner** [comment]
Alright, I haven't tried nuitka yet, but specifically for PyInstaller there is a special "extension" with instructions on how to package Flet binaries into resulting excutable: https://github.com/flet-dev/flet/tree/main/sdk/python/flet/__pyinstaller

If you are familiar with nuitka you may take a look if it provides the same mechanism. Otherwise, if Flet binaries are missing from the package it tries to download them on the first start which could be problematic without internet access.

**Comment by tomasky** [comment]
sorry ,i am later , I don't find a similar solution in nuitka, maybe this, but  I haven't tested it yet

```bash
nuitka3  –module flet –include-package=flet    --onefile  hello.py
```
