### ISSUE TITLE
Controls data property is null on v0.1.54

### ISSUE THREAD

**Issue by nasoma** [flet-dev/flet#240]
Post v0.1.52  a controls data property now returns null.

``` 
 c2 = Container(
        data=20,
        ink=True,
        content=Text("KShs 20", size=20, color=colors.BLACK54, weight="w600"),
        margin=10,
        padding=padding.symmetric(vertical=30),
        alignment=alignment.center,
        bgcolor=colors.SURFACE_VARIANT,
        border=border.all(1, "#7284A8"),
        width=100,
        height=100,
        border_radius=0,
        on_click=compute,
        expand=1,
    )
```
On firing an event e.data is now null instead of 20 as in the example above. On v0.1.52 the correct value (20) was returned.

**Comment by FeodorFitsner** [comment]
Ah, it's a good note, thanks for pointing that out!

So, before v0.1.54 `Control.data` is used to send its value to Flet server and thus Flutter UI with every page update. In some controls `data` property value was returned in event's `data`. It was a "legacy" solution that was migrated from Pglet where it wasn't easy way to know which control generated the event.

Now `Control.data` is not used in the event callback and always stays a client - Python program: https://github.com/flet-dev/flet/commit/67fe7136f8ff5616d6e91bf8821de88809a480e3#diff-bacf19c2b12a8f3ef9649e54432fb3beeffdd0b90fdbe380448d418f566d9eeb  

Also, `data` value is not placed into control attributes anymore: https://github.com/flet-dev/flet/commit/67fe7136f8ff5616d6e91bf8821de88809a480e3#diff-153f8fef463d23c67097e593f496229e6bb89e81ee984c450812932d1db2af43R292-R298

In the event handler instead of checking `e.data` you should use `e.control.data` which is original, unmodified value:

```python
import flet
from flet import ElevatedButton, Page

def main(page: Page):
    def button_click(e):
        print(e.control.data)

    page.add(
        ElevatedButton(text="Test button", data=20, on_click=button_click),
    )
    page.update()

flet.app(target=main)
```

Like now you can put not just literal into `Control.data` but any object.

**Comment by nasoma** [comment]
Ah! Perfect!
