### ISSUE TITLE
I'm confused, I'm using flex run xxx.py and python.exe xxx.py  The results obtained are different

### ISSUE THREAD

**Issue by laowus** [flet-dev/flet#2524]
I'm confused, I'm using flex run xxx.py and Python xxx.py

The results obtained are different

My project has set up a virtual environment, and I'm not sure if this is the reason, 
but the Python version installed on my computer is the same 3.10

**Comment by taaaf11** [comment]
Please give the minimal reproducable code.

**Comment by Judenilson** [comment]
> I'm confused, I'm using flex run xxx.py and Python xxx.py
> 
> The results obtained are different
> 
> My project has set up a virtual environment, and I'm not sure if this is the reason, but the Python version installed on my computer is the same 3.10

You saved me! I spent two days trying to solve a problem because I ran the program using Flet -d main.py! When I used Python main.py it worked! Thank you!!!

I have a method triggered by an elevated button that moves many folders to another location, but it was only copying two and then it would stop copying without showing any errors. If I called the method again using the same elevated button, it would copy two and two folders every time I pressed the button. But, using Python main.py the program worked perfectly.

I use python 3.12.2 windows 11

**Comment by huangxulei** [comment]
> > I'm confused, I'm using flex run xxx.py and Python xxx.py
> > The results obtained are different
> > My project has set up a virtual environment, and I'm not sure if this is the reason, but the Python version installed on my computer is the same 3.10
> 
> You saved me! I spent two days trying to solve a problem because I ran the program using Flet -d main.py! When I used Python main.py it worked! Thank you!!!
> 
> I have a method triggered by an elevated button that moves many folders to another location, but it was only copying two and then it would stop copying without showing any errors. If I called the method again using the same elevated button, it would copy two and two folders every time I pressed the button. But, using Python main.py the program worked perfectly.
> 
> I'm using python 3.12.2 windows 11
yes, `flet run xx.py -d ` have some bugs ,  It's best to use `python xx.py`
