### ISSUE TITLE
apk build fails with requirements.txt

### ISSUE THREAD

**Issue by praskuma** [flet-dev/flet#3167]
There is something strange I observed.

As long as there is no requirements.txt
or requiremnets.txt is empty

flet build apk --verbose
works fine

The moment you add a module(let it be any module) to requirements,txt,
"flet build apk --verbose"
gets stuck at
"Extracting Python distributive from"

OS: Windows
Flet : 0.22.0

**Comment by praskuma** [comment]
just fyi im trying to include 
yfinance
into requirements.txt

**Comment by praskuma** [comment]
C:\ex\py\ap>flutter --version
Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (2 weeks ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1

**Comment by zox47** [comment]
The same problem with me

**Comment by JustinMissmahl** [comment]
same problem here trying to build a apk including web3 


flet==0.22.1
aiohttp==3.9.5
web3==7.0.0b5

**Comment by praskuma** [comment]
Can someone please look into this or give some clue.

**Comment by baseplate-admin** [comment]
@praskuma, the reason you cant build that apk is because 

Yfinance internally depends on:
* [numpy](https://github.com/ranaroussi/yfinance/blob/e238ac1f9501c2ec3e1bbb72df85935c0522bf92/requirements.txt#L2)
* [pandas](https://github.com/ranaroussi/yfinance/blob/e238ac1f9501c2ec3e1bbb72df85935c0522bf92/requirements.txt#L1)
* [html5lib](https://github.com/ranaroussi/yfinance/blob/e238ac1f9501c2ec3e1bbb72df85935c0522bf92/requirements.txt#L10)
* [lxml](https://github.com/ranaroussi/yfinance/blob/e238ac1f9501c2ec3e1bbb72df85935c0522bf92/requirements.txt#L5)

These are native applications and they probably dont have a recipe in the[ `python-for-android` ](https://github.com/kivy/python-for-android) repo

> The moment you add a module(let it be any module) to requirements,txt,

To be honest flet support for any module is lackluster at this moment. If you want to see support of flet for modern android you should follow this[ repo](https://github.com/flet-dev/python-mobile)

**Comment by baseplate-admin** [comment]
@JustinMissmahl, `aiohttp` is not available for android

**Comment by praskuma** [comment]
@baseplate-admin thanks for the details.

Sure  i will try out 

https://github.com/flet-dev/python-mobile
and update.

**Comment by baseplate-admin** [comment]
@praskuma, `python-mobile` will be used internally by `flet`. 

@FeodorFitsner  can update you on this

**Comment by praskuma** [comment]
So can I assume, if I use yfinance...building apk is not possible at this moment?

**Comment by baseplate-admin** [comment]
Yes, for now you cant build apk.

Check https://github.com/flet-dev/flet/issues/2714#issuecomment-2119375529 comment by @FeodorFitsner . He will roll out support for building python binary for android soon.

**Comment by praskuma** [comment]
Thanks for the update.....ragarl6 waiting for the support

Let me tell you....
"flet build apk" command came in as a surprise to me....din't know building apk was so simple.

You folks are doing great work. Keep it up.

**Comment by praskuma** [comment]
> Yes, for now you cant build apk.
> 
> Check [#2714 (comment)](https://github.com/flet-dev/flet/issues/2714#issuecomment-2119375529) comment by @FeodorFitsner . He will roll out support for building python binary for android soon.

Just a follow-up, any update on this.

**Comment by ndonkoHenri** [comment]
Closing in favour of https://github.com/flet-dev/flet/issues/3839
