### ISSUE TITLE
Cannot use Markdown in a Container

### ISSUE THREAD

**Issue by B3J4y** [flet-dev/flet#359]
**Description**

I try to render md files in my app and thought it would be good to put them into a container. Especially because I need to show multiple md files in one page. But after putting them into a container, flet didn't display anything.

**Code example to reproduce the issue:**

```python
random_markdown_element = Markdown(random_md, selectable=True, extension_set="commonMark",
                        on_tap_link=lambda e: page.launch_url(e.data), expand=True)
page.add(Container(content=random_markdown_element))
```

Is there a way to containerize Markdown, or is this not provided for?

**Comment by hololeo** [comment]
container needs width or height

**Comment by B3J4y** [comment]
Height is needed. If I just use width, then nothing happens. It would be helpful to document it in https://flet.dev/docs/controls/container/ that height is mandatory.  

Now I have to measure the height of the component in absolute units or is there also a possibility to set a relative value dependent on the window size.

Thank you for your help.

**Comment by modaye** [comment]
#331 There are similar problems here

**Comment by FeodorFitsner** [comment]
So, the problem is that to implement markdown Flet uses `Markdown` widget which is `MarkdownBody` wrapped into `ListView`. That's why it requires either fixed height or expand.

I've just fixed `Markdown` control to use `MarkdownBody`. It's going to be responsibility of Flet developer to put it into a scrollable container.

Markdown in container:

![image](https://user-images.githubusercontent.com/5041459/191351691-26cc8a5f-627d-496d-a1b7-eff95f59b351.png)

```python
        Container(
            Markdown(
                md2,
                extension_set="gitHubWeb",
                on_tap_link=lambda e: page.launch_url(e.data),
            ),
            width=200,
            bgcolor="#f5f5f5",
            border=border.all(2, "blue"),
            border_radius=10,
            padding=10,
            clip_behavior="antiAlias",
        )
```
