### ISSUE TITLE
bug: filepicker returning 'cancel' on pick/save/open directory - osx

### ISSUE THREAD

**Issue by hololeo** [flet-dev/flet#365]
**Description**

Tried to run examples of file picker but does not work. It returns 'cancelled' error message. see gif

**Code example to reproduce the issue:**

```python
see https://github.com/flet-dev/examples/blob/main/python/controls/file-picker/file-picker-all-modes.py
```

**Describe the results you received:**

![flet_filepicker_bug](https://user-images.githubusercontent.com/11970940/191411486-9d760256-5c6e-41dc-b191-5bdcff9200d1.gif)

**Describe the results you expected:**

Pick file, save file, open directory, world peace, etc 

**Flet version (`pip show flet`)**:

```
0.1.57
```

**Operating system**:

Mac OSX 10.14 (Mojave)

**Comment by FeodorFitsner** [comment]
On macOS file picker uses `osascript` to implement dialogs:
https://github.com/miguelpruivo/flutter_file_picker/blob/master/lib/src/file_picker_macos.dart#L18

My quick guess would be there is something wrong with permissions to that tool on your Mac, not because it's Mojave.
Maybe you can try building `osascript` command based on [this](https://github.com/miguelpruivo/flutter_file_picker/blob/master/lib/src/file_picker_macos.dart#L127) and call that command directly from a Python app to see what's going on?

**Comment by hololeo** [comment]
thanks for that line of inquiry. im googling the rabbit trail 
here are my research links so far

https://discussions.apple.com/thread/254186467
https://scriptingosx.com/2020/09/avoiding-applescript-security-and-privacy-requests/
https://developer.apple.com/forums/thread/110469

**Comment by FeodorFitsner** [comment]
You see that in your console?

**Comment by hololeo** [comment]
no mac console app, has a tab on left for system.log

https://www.howtogeek.com/406592/how-to-use-the-console-on-macos-to-check-log-and-activities/

https://www.howtogeek.com/wp-content/uploads/2019/03/img_5c7ba8de1daa3.png?width=1198&trim=1,1&bg-color=000&pad=1,1

**Comment by FeodorFitsner** [comment]
Got it working?

**Comment by hololeo** [comment]
no i gave up on that atm

**Comment by FeodorFitsner** [comment]
Let's close it for now. If anyone else experience this issue it could be re-opened.
