### ISSUE TITLE
--add-data doesn't work when i pack 

### ISSUE THREAD

**Issue by asil004** [flet-dev/flet#3840]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

when i use 
`flet pack your_program.py --add-data "assets:assets"`
command for packing. assests doesn't work no images icons.

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Linux

### Operating system details

Debian 11.04

### Flet version

0.23.2 

### Regression

No, it isn't

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by zhiqiu-yiye** [comment]
Windows also has the same issue

**Comment by mandar1n0** [comment]
I think I have a solution, at least it worked for me:

1. main.py should have this line al the end of the file:
`ft.app(target=main, assets_dir="assets")`
2. assets folder should be at the same level of main.py and all the images should go in the images folder inside assets
3. use this function to reference the assets for develop and build: 

```
import os
import sys

def resource_path(relative_path):
    
base_path = getattr(sys, '_MEIPASS', os.path.abspath("."))
return os.path.join(base_path, relative_path)
```
5. and then use it like this:

```
ft.Image(
                        src=resource_path(f"assets/images/profilepic.png"),
                        width=100,
                        height=100,
                        fit=ft.ImageFit.CONTAIN,
                    )
```
6. finally when using pack command reference the icon (if you have) and asset folder (this is for windows, mac os and linux use : separator instead of ;)

`flet pack main.py --icon assets/icon.ico --add-data "assets;assets"`

**Comment by SKD8** [comment]
Does not work with Flet Build command
