### ISSUE TITLE
`TextField.value`'s type hint

### ISSUE THREAD

**Issue by ndonkoHenri** [flet-dev/flet#591]
**Description**

`TextField.value` can take both a `str` and a number. But its type hint in `textfield.py` is `Optional[str] = None`(either `str` or `None`)
The type hint should be updated, if you think this behavior is normal.

**Code example to reproduce the issue:**

```python
import flet as ft

def main(page: ft.Page):

    tb1 = ft.TextField(value=2500)
    tb2 = ft.TextField(value="2500")

    page.add(tb1, tb2)

ft.app(target=main)
```

**Comment by FeodorFitsner** [comment]
It shows error which is correct. It's supposed to accept strings only.

I could add beartype decorator to enforce strings at runtime. Would that work?

![image](https://user-images.githubusercontent.com/5041459/203386159-213d7538-1d17-40fe-86e4-a346ea74e94d.png)

**Comment by ndonkoHenri** [comment]
Oh. 
Alright. Why not give it a try. 🤷🏽‍♂️
I personally don't know if it will work. (Don't know how to use beartype yet)

**Comment by ndonkoHenri** [comment]
hey!
worked as expected?

**Comment by FeodorFitsner** [comment]
No, I decided to leave it as is. Adding beartype check breaks a lot.
Let it show the error during code editing.

**Comment by ndonkoHenri** [comment]
Alright.

**Comment by iron3oxide** [comment]
Why is value an Optional? I just tried out the counter example from the docs and pyright complained that the TextField value that is manipulated in the callback functions can be None. 

It of course isn't, because it gets set when the TextField is created, but is it not more intuitive to say that a TextField always has a value and that its default value is an empty string?

Sorry if this is obvious, I am not familiar with the code yet.
