### ISSUE TITLE
Flet CLI to run an app from a module?

### ISSUE THREAD

**Issue by rajiteh** [flet-dev/flet#702]
I was wondering if its possible use the flet-cli with a module instead of a script? Thanks!

**Comment by rajiteh** [comment]
Well my use case is about adding a simple web ui to a pre-existing CLI tool, so the flet server is not invoked through a specific entrypoint script rather a method inside a python package. While developing, I was able to continue using my existing workflows (vscode python debugger) to a great extent with flet side of things but I find lack of hot-reloading inconvenient sometimes, specially when messing around with layouts of my components.

Then I discovered the flet-cli but I couldn't figure out how to make it launch my tool with the correct arguments as I'm using `python -m path/ <some args>`  to start it.

May be I'm on the wrong track here, would love to hear any opinions on this use case or if there are any alternatives that I could do to make it work?  
Thanks!

**Comment by michasng** [comment]
This is an important issue, because otherwise hot reload triggers on changes other than the source code, which I believe is not intended.
To elaborate, consider this project structure:

my_project
├── my_module
│   ├── __init__.py
│   └── __main__.py
├── tests
│   ├── ...
└── pyproject.toml # for example, could also be requirements.txt or whatever

Here, I would like to run `my_module/__main__.py` with hot reload, so that any code changes in `my_module` are immediately reflected in my app. This would be possible, if I could just run `flet run -m my_module -r` like when running other python projects. It's not possible right now without `-m` , because absolute imports in `__main__.py` don't work, because `my_project/my_module` is now on the `sys.path`.

What I currently have to do instead is either have no hot reload or move `__main__.py` into `my_project` and use `flet run __main__.py  -r`, but that means that any changes to the project directory trigger a hot reload. This is unfortunate, if you are for instance writing log files to the project directory or if you make changes to some other parts of the project. Those changes trigger a hot reload.
