### ISSUE TITLE
Changing multiple references of the same control is not reflected on UI

### ISSUE THREAD

**Issue by FeodorFitsner** [flet-dev/flet#764]
Code to reproduce the issue:

```python
import flet as ft

def main(page):
    tv = ft.Text("Foo")
    page.add(tv, tv)

    tv.value = "Bar"
    page.update()

ft.app(target=main)
```

Expected result:

```
Bar
Bar
```

Actual result:

```
Foo
Bar
```

**Comment by apumapho** [comment]
The issue, as you suspected @FeodorFitsner because you wrote it 😄, is the control.uid gets incremented and set each time the control is added to the page on initial page build:

https://github.com/flet-dev/flet/blob/14c215b0194ae94ebf87aef8efe7b1aaf6e1ee7e/sdk/python/flet/page.py#L389-L392

The result is a `page.controls` tree that looks like this:

```
def main(page):
    tv = ft.Text("Foo")
    page.add(tv, tv)

    for i, control in enumerate(page.controls):
        print(f"control[{i}]: {control}, control.uid: {control.uid}")
```

Result:

```
control[0]: control: <flet.text.Text object at 0x102a829b0>, control.uid: _3  # should be _2 but can't be given implementation
control[1]: control: <flet.text.Text object at 0x102a829b0>, control.uid: _3
```

Later, when the control is updated, it's `dirty` attribute is set to False the first time the `control._build_command()` method is called from within `control.update_build_commands()`:

https://github.com/flet-dev/flet/blob/14c215b0194ae94ebf87aef8efe7b1aaf6e1ee7e/sdk/python/flet/control.py#L453

Because of the above, and the fact that all the Text controls in your example share the same `uid`, `_update_command()` is only going to return the needed set command one time for multiple references to the same control:

```
Command(indent=0, name=None, values=['_3'], attrs={'value': 'Bar'}, commands=[])
```

Happy to try to resolve. Planning to investigate extending `page._index` dict to store extra info that maps the *specific* control to it's correct `uid`.

**Comment by FeodorFitsner** [comment]
That's right, because those are all the references to the same object.

**Comment by FeodorFitsner** [comment]
Closing as "as designed".
