### ISSUE TITLE
[Feature Request] PDF preview/printing

### ISSUE THREAD

**Issue by iron3oxide** [flet-dev/flet#894]
**Please Describe The Problem To Be Solved**

Currently it is not possible to display a PDF in a widget that allows printing or saving it.

**(Optional): Suggest A Solution**

The following flutter package looks like the most viable one to provide that functionality:
https://pub.dev/packages/printing

**Comment by Shahin-rmz** [comment]
I second this.
For my app, I need to show pdfs in each page.
any idea if the feature will be implemented?

**Comment by DanielRios549** [comment]
I also need a feature to show a PDF. I was using CLI to create a PDF using `reportlab` package, now I am create an UI with Flet and I need to preview the PDF before saving

**Comment by Petercadeau** [comment]
![image](https://user-images.githubusercontent.com/48536105/216525354-72634bc6-45a2-40b2-9e60-df6447feffe7.png)
I have that approximation, where I convert each page into an image to be able to show you

**Comment by Shahin-rmz** [comment]
> I have that approximation, where I convert each page into an image to be able to show you

Please let me disagree.
Users should be able to select text from PDF if it's needed.

**Comment by saurabhwadekar** [comment]
@iron3oxide 

I tried it but converting pdf to image will not be a good decision By doing this, 
some problems may have to be faced. 

1) I opened a 60 page PDF which used 1.3GB of RAM 

2) It loads very slowly 

3) There may be a possibility of app crash due to consuming more RAM 

4) Text search cannot be done 

5) Text cannot be selected

**Comment by zzj0402** [comment]
What's the completed solution for this?
