### ISSUE TITLE
Path gets reset when user manually changes it

### ISSUE THREAD

**Issue by kkinder** [flet-dev/flet#982]
**Description**

The user cannot manually change the URL of a page they're visiting with Flet. Consider this simple Flet example and watch the following screencast.

https://user-images.githubusercontent.com/1115018/216831157-d27bf814-a2e2-4fe7-a538-fffe0541c930.mp4

**Code example to reproduce the issue:**

```python
import flet as ft


def main(page: ft.Page):
    page.add(
        ft.Text(f"This is the path: {page.route}")
    )


if __name__ == "__main__":
    flet_path = ''
    flet_port = 8001
    ft.app(name=flet_path, target=main, view=None, port=flet_port, route_url_strategy="path")
```

**Describe the results you received:**

When the user tries to change a URL, in an existing window, the URL reverts.

**Describe the results you expected:**

The user should be able to update the URL, as is normal with web sites.

**Additional information you deem important (e.g. issue happens only occasionally):**

If you open a _new tab_, and enter a URL there, it works. However, modifying an existing tab (open to a Flet app) does not allow for URL changes done by the user.

**Flet version (`pip show flet`)**:

```
Name: flet
Version: 0.4.0
Summary: Flet for Python - easily build interactive multi-platform apps in Python
Home-page:
Author: Appveyor Systems Inc.
Author-email: hello@flet.dev
License: MIT
Location: /Users/kkinder/Library/Caches/pypoetry/virtualenvs/fletend-9mHHD83p-py3.11/lib/python3.11/site-packages
Requires: flet-core, httpx, oauthlib, packaging, watchdog, websocket-client, websockets
Required-by:
```

**Operating system**:

Version 13.2 (22D49)

**Additional environment details:**

Poetry (version 1.3.1)

**Comment by iron3oxide** [comment]
Just ran into the same issue. It seems the `RouteChangeEvent` just doesn't fire.

**Comment by iron3oxide** [comment]
Investigated a bit: the event handler converter method, called `convert_route_change_event()` in `page.py` seems to get called when one manually changes the route. However, that change doesn't result in a `RouteChangeEvent' being returned because for some reason, the data of the event it converts always contains an unchanged route and thus `None` is returned from a guard clause.

**Comment by gbrandt** [comment]
This only occurs when url strategy is set to "path", "hash" works as expected.  This does not occur on Safari because safari actually does an entire page load on manual url change.  Brave, Chrome and Firefox do not.

**Comment by gbrandt** [comment]
Still occurs in 0.5.2.  Its not an option to use hash paths for me, even temporarily because I am replacing an existing app and need to use the same paths.

**Comment by gbrandt** [comment]
yes, on a new tab you can paste a link in and it works as expected.  However, I have never seen an app that does not allow me to navigate by typing in URLs if I chose to.

My use case is that a user can get a 'public' link to an object which they can paste into the URL bar, but if they are also a  member of the site, they get more actions available to them on the public page. So they go to the login window, login, then paste the public URL back in, but it fails and they can never see the public link again without opening a new tab.  This is very surprising to the user because they expect that typing an URL will do the right thing.

**Comment by FeodorFitsner** [comment]
Will take a look.
